apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service.yaml
  - hpa.yaml

patches:
  - path: deployment_patch.yaml

labels:
  - includeSelectors: true
    pairs:
      app: oai-pmh
