apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-pmh-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: oai-pmh
          image: europeana/oai-pmh
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 100
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 80
            periodSeconds: 30
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/oai-pmh.user.properties"
              readOnly: true
              subPath: oai-pmh.user.properties
      volumes:
        - name: secret
          secret:
            secretName: oai-pmh-secret