apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: oai-pmh

# expects files to be in the same directory
secretGenerator:
  - name: oai-pmh-secret
    files:
      - oai-pmh.user.properties
